### PR TITLE
Merge MVP to Main branch 

### PR DESCRIPTION
**Pull request by imOnVacation**
## public/ about.css & about.html - @rsanch2 [issue #31](https://github.com/PSU-MCECS-SAFE/SAFE/issues/31#issue-1698165345)
The about page for this project gives a short description of what SAFE is as well as gives users the chance to see how their identities will remain anonymous while using the system.

## safe_setup.py - @NAlexH2  [issue #27](https://github.com/PSU-MCECS-SAFE/SAFE/issues/27#issue-1697069201)
This python script allows devs and owners to quickly setup and/or rebuild all/part of the code to be deployed without having to sweat overhead work of ensuring they are clearing the correct files or setting up the system from the start correctly.

### Features:
- Menu to enable various usage capabilities
image
   - Option 1 should always be ran first time the script is ran. This option first generates the configuration file, builds and then sets necessary permissions for specific files and folders to be visible by the PSU apache server. It executes every required step on initial setup that enables the entire website to come on line for the CECS/MCECS PSU web servers.
   - Other options enable real time rebuilding while editing code to support live development without `npm run start` by targeting specific key resources to be rebuilt as requested.
   - This script can sit in the background ***AFTER*** option 1 has been executed and a developer is working on testing various components outside of `npm run start` if need be.
- This script ensures a number of system safeties before trying to execute various commands
   - If the system is a Windows like system, `chmod` is never called. `chmod` is and only ever called on Unix like systems. 
   - Other types of operating systems have not been accounted for.
- This script can be ran directly and have a command line argument `-d` to enable debug mode
  - Can also call `npm run debug_deploy` to get the same effect of running the script in debug mode.
  - Debug mode gives normal, non-verbose output, for all commands that are called.
- This script also checks for various `hostname`s to ensure that it's not accidentally ran where it shouldn't be.
  - A regex examines the systems `hostname`, if it isn't apart of the regex, the script returns a message. Otherwise it proceeds as expected.

## safeMessageDB/ messageDBConnect.ts & server.ts - @Vincentmask [issue #32](https://github.com/PSU-MCECS-SAFE/SAFE/issues/32#issue-1698307840) and [issue #33](https://github.com/PSU-MCECS-SAFE/SAFE/issues/33#issue-1698310265)
- messageDBConnect.ts

This is what should be imported whenever we need to connect to the database.
It export the 'messageDBConnect' to be a new Pool from pg which can later on to use .connect to retrieve a pg client to start the database work process.

The database login information is hide behind the scene, it will call Util class' getConfigProp function to retrieve the information needed
- server.ts

This is the server code to transfer data between the front end and back end.

It is a server using Express.

It can use request methods including but not limited to Get, Post, Put, and Delete. And these methods have to provide endpoints for frontend code to work.

It requires importing from messageDBConnect and using .connect to retrieve a pg client to start doing database work.

Front-end code can fetch the endpoint and execute these methods, and the endpoints can return a response status to let the frontend knows what was going on.

## safeUI/ SafeUI.tsx & Styled.tsx - @jeffmchale [issue #35](https://github.com/PSU-MCECS-SAFE/SAFE/issues/35#issue-1700646169) and [issue #36](https://github.com/PSU-MCECS-SAFE/SAFE/issues/36#issue-1700650917)
- SafeUI.tsx

Frontend code for sender side UI. Page primarily built in MaterialUI with focus on responsive design. Handles feedback submissions made to system. 

Contains a form (To:, Subject:, Message fields) that only accepts submission (on button click) if all form elements are filled in.  

Further information can be found in site external links to better understand how sender anonymity is handled or Title 9 reporting concerns. 

~~Google's ReCaptcha V3 sits behind client to help mitigate spam~~ (Not in current implementation) 

Once fields are filled appropriately and submitted, established endpoint (from Server.ts) will be used to make Post request to database, completing a sender feedback submission. 

- Styled.tsx

Simple exported function used to override the basic submit button styles in SafeUI.tsx. Button has been overridden to provide minor styling differences from stock component, like PSU-green color and transition color effect once clicked. 

## safeUtil/ Util.ts - @NAlexH2 [issue #28](https://github.com/PSU-MCECS-SAFE/SAFE/issues/28#issue-1697075485)
General utility function(s) to be used in the project. As of this issue and **Pull Request** #19  it holds...

- `safeJSONProps` is an enum to be used and passed to `getConfigProp` based on specific values requested from the `safeConfig.json` generated by `makeConfigFile` in found in `safe_setup.py` (**See issue** #27)
- A `const` absolute path to where `safeConfig.json` lives. Utilized elsewhere in the systems code.
- `getConfigProp` which takes a `prop` as a `string` from the enum `safeJSONProps` such that no conflicts can arise from attempting to access a value that doesn't exist. `getConfigProp` also takes the path mentioned above (or another if needed) such that it too doesn't fail if using the default configuration.

## tests/ UI.tests.tsx & Util.test.tsx & server.test.tsx
- UI.test.tsx 
    - render test 
    - render the form elements test
    - render the welcome msg and subtitle test
    - submit with valid input test 
    - submit with empty input test
    - character count msg and subject test
- Util.test.tsx
JSON file property acquisition test
- server.test.tsx
None test for now

## .gitignore & package.json & package-lock.json & tsconfig.json
Installed all necessary packages to implement the MVP and gitignore config setting

## All others
- Removed unnecessary starting files 
- Added PSU icon and logo
- Changed index background color

### CODE REVIEW

**Comment by NAlexH2** [comment]
`safe_script.py` information resolved #27 
`Util.ts` requested information resolved #28 

@imOnVacation Feel free to close these once you've copied the details over.

**Comment by NAlexH2** [comment]
`safe_script.py` information resolved #27 
`Util.ts` requested information resolved #28 

@imOnVacation Feel free to close these once you've copied the details over.

**Review by NAlexH2 — APPROVED** [review]

**Review by Vincentmask — APPROVED** [review]
lgtm

**Review by dylanconklin — APPROVED** [review]

**Review by rsanch2 — APPROVED** [review]

**Review by McJefe — APPROVED** [review]
Looks good. In future, SafeUI.tsx can/should be updated to support a more modular design. Components should be separated out so SafeUI() is easier to debug and understand.

**Review by MrFiszbi1 — APPROVED** [review]

**Review by MrFiszbi1 — APPROVED** [review]

**Review by MinhDucMa97 — APPROVED** [review]

**Pull request merged**
