### PR TITLE
Dev message

### PR DESCRIPTION
**Pull request by NAlexH2**
In this PR:

1. Recognized that the original message class was not required and was removed in lieu of passing in the information directly to/from the DB.
2. Functions to facilitate to getting and inserting messages from/to the database.

### CODE REVIEW

**Review by imOnVacation — APPROVED** [review]
- Great idea on using ResultRow<Client.Value>[] from ts-postgresql 
- Message.test.tsx need to remove since there is no message class

**Review by Vincentmask — APPROVED** [review]
Looks good but I don't see the Message class, so I think we need to re-write the tests?

**Review by McJefe — APPROVED** [review]
Outside of the minor issue the others had mentioned, this looks good guys.

**Comment by NAlexH2** [comment]
> Looks good but I don't see the Message class, so I think we need to re-write the tests?

I agree. We can postpone merging this till we get t hat resolved.

**Comment by NAlexH2** [comment]
Branch no longer required.

**Pull request closed without merging**
